# Generated by Django 5.0.6 on 2026-06-15 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('key_insights', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_results',
            },
        ),
        migrations.CreateModel(
            name='ZoneScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.CharField(choices=[('communication', 'Коммуникация'), ('trust', 'Доверие'), ('intimacy', 'Близость'), ('conflict', 'Конфликты'), ('values', 'Ценности'), ('future', 'Будущее')], max_length=30)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'zone_scores',
            },
        ),
    ]
