# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsresult',
            name='session_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_as_a', to='diagnostics.diagnosticsession'),
        ),
        migrations.AddField(
            model_name='analyticsresult',
            name='session_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_as_b', to='diagnostics.diagnosticsession'),
        ),
        migrations.AddField(
            model_name='zonescore',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_scores', to='analytics.analyticsresult'),
        ),
    ]
