# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='zonescore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsresult',
            index=models.Index(fields=['couple', '-created_at'], name='analytics_r_couple__05c15a_idx'),
        ),
        migrations.AddIndex(
            model_name='zonescore',
            index=models.Index(fields=['result', 'zone'], name='zone_scores_result__1cddb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zonescore',
            unique_together={('result', 'zone', 'user')},
        ),
    ]
