# Generated by Django 5.0.6 on 2026-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsresult',
            name='bridge_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsresult',
            name='child_environment_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='analyticsresult',
            name='crisis_level',
            field=models.CharField(choices=[('none', 'Нет'), ('warning', 'Предупреждение'), ('critical', 'Кризис')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='analyticsresult',
            name='finance_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='analyticsresult',
            name='problem_chain',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsresult',
            name='relatives_index',
            field=models.CharField(blank=True, choices=[('low', 'Низкое'), ('medium', 'Среднее'), ('high', 'Высокое')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analyticsresult',
            name='strengths_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
