# Generated by Django 5.0.6 on 2026-06-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimessage',
            name='tokens_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
