# Generated by Django 5.0.6 on 2026-06-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0006_data_migrate_coach_conversations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiconversation',
            new_name='ai_conversa_dialog__7bfd53_idx',
            old_name='ai_conversa_dialog__type_idx',
        ),
    ]
