# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='partner_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couple',
            name='partner_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples_as_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupleinvite',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='couples.couple'),
        ),
        migrations.AddField(
            model_name='coupleinvite',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['partner_a'], name='couples_partner_4586ef_idx'),
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['partner_b'], name='couples_partner_845650_idx'),
        ),
        migrations.AddIndex(
            model_name='couple',
            index=models.Index(fields=['status'], name='couples_status_ead9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='coupleinvite',
            index=models.Index(fields=['token'], name='couple_invi_token_fd2094_idx'),
        ),
        migrations.AddIndex(
            model_name='coupleinvite',
            index=models.Index(fields=['couple'], name='couple_invi_couple__3dd2dd_idx'),
        ),
    ]
