# Generated by Django 5.0.6 on 2026-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='children_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couple',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couple',
            name='marriage_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
