# Generated by Django 5.0.6 on 2026-06-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0005_seed_family_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
