# Generated by Django 5.0.6 on 2026-06-15 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0003_couple_children_count_couple_has_children_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyConstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('values', models.JSONField(blank=True, default=list)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('communication_rules', models.JSONField(blank=True, default=list)),
                ('conflict_rules', models.JSONField(blank=True, default=list)),
                ('finance_principles', models.JSONField(blank=True, default=list)),
                ('parenting_approach', models.JSONField(blank=True, default=list)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constitution', to='couples.couple')),
            ],
            options={
                'db_table': 'family_constitutions',
            },
        ),
    ]
