# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_scale', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('value_choice', models.CharField(blank=True, max_length=100, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('abandoned', 'Брошена')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagnostic_sessions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.CharField(choices=[('communication', 'Коммуникация'), ('trust', 'Доверие'), ('intimacy', 'Близость'), ('conflict', 'Конфликты'), ('values', 'Ценности'), ('future', 'Будущее')], max_length=30)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('scale', 'Шкала 1-5'), ('choice', 'Выбор варианта'), ('text', 'Текст')], default='scale', max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('order_index', models.SmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['zone', 'order_index'],
            },
        ),
    ]
