# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0002_initial'),
        ('diagnostics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='couples.couple'),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostics.diagnosticsession'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['zone', 'is_active'], name='questions_zone_5df465_idx'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.question'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['couple', 'user'], name='diagnostic__couple__183dba_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['status'], name='diagnostic__status_60fb19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticsession',
            unique_together={('couple', 'user')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['session'], name='answers_session_a75fdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('session', 'question')},
        ),
    ]
