# Generated by Django 5.0.6 on 2026-06-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_diagnosticsession_index_update'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diagnosticsession',
            new_name='diagnostic__couple__bba3f3_idx',
            old_name='diagnostic_sessions_couple_user_level_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_level_n_9abfc4_idx',
            old_name='questions_level_active_idx',
        ),
    ]
