# Generated by Django 5.0.6 on 2026-06-15 23:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0003_couple_children_count_couple_has_children_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Конфликт', max_length=300)),
                ('status', models.CharField(choices=[('collecting', 'Сбор описаний'), ('analyzing', 'Анализ'), ('complete', 'Завершён')], default='collecting', max_length=20)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_sessions', to='couples.couple')),
            ],
            options={
                'db_table': 'conflict_sessions',
            },
        ),
        migrations.CreateModel(
            name='ConflictEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('feelings', models.TextField(blank=True, default='')),
                ('desired_outcome', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mediation.conflictsession')),
            ],
            options={
                'db_table': 'conflict_entries',
            },
        ),
        migrations.AddIndex(
            model_name='conflictsession',
            index=models.Index(fields=['couple', '-created_at'], name='conflict_se_couple__e7fbc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conflictentry',
            unique_together={('session', 'user')},
        ),
    ]
