# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.SmallIntegerField()),
                ('day_of_week', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('exercise', 'Упражнение'), ('question', 'Вопрос'), ('reading', 'Чтение'), ('practice', 'Практика')], default='exercise', max_length=30)),
                ('assigned_to', models.CharField(choices=[('both', 'Оба'), ('partner_a', 'Партнёр A'), ('partner_b', 'Партнёр B')], default='both', max_length=20)),
                ('order_index', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'plan_tasks',
                'ordering': ['week_number', 'day_of_week', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_completions',
            },
        ),
        migrations.CreateModel(
            name='RecoveryPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('duration_weeks', models.SmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершён'), ('paused', 'Пауза')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='couples.couple')),
            ],
            options={
                'db_table': 'recovery_plans',
            },
        ),
    ]
