# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0004_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recoveryplan',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.analyticsresult'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.recoveryplan'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='plans.plantask'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recoveryplan',
            index=models.Index(fields=['couple', 'status'], name='recovery_pl_couple__d365b8_idx'),
        ),
        migrations.AddIndex(
            model_name='plantask',
            index=models.Index(fields=['plan', 'week_number'], name='plan_tasks_plan_id_b2f588_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['task'], name='task_comple_task_id_d9c5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcompletion',
            index=models.Index(fields=['user'], name='task_comple_user_id_2ae714_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('task', 'user')},
        ),
    ]
