# Generated by Django 5.0.6 on 2026-06-15 23:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0003_couple_children_count_couple_has_children_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPractice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('question_of_day', models.TextField()),
                ('conversation_topic', models.TextField()),
                ('trust_exercise', models.TextField()),
                ('communication_exercise', models.TextField()),
                ('family_activity', models.TextField()),
                ('romantic_idea', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_practices', to='couples.couple')),
            ],
            options={
                'db_table': 'daily_practices',
            },
        ),
        migrations.CreateModel(
            name='PracticeCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=50)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='practices.dailypractice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practice_completions',
            },
        ),
        migrations.AddIndex(
            model_name='dailypractice',
            index=models.Index(fields=['couple', '-date'], name='daily_pract_couple__2c02b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypractice',
            unique_together={('couple', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='practicecompletion',
            unique_together={('practice', 'user', 'field_name')},
        ),
    ]
