# Generated by Django 5.0.6 on 2026-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0006_family_development_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['category', 'slot_type', 'difficulty', 'title']},
        ),
        migrations.RenameIndex(
            model_name='dailyassignment',
            new_name='daily_assig_couple__a6e8c8_idx',
            old_name='daily_assign_couple_date_idx',
        ),
        migrations.AlterField(
            model_name='practice',
            name='category',
            field=models.CharField(choices=[('communication', 'Коммуникация'), ('trust', 'Доверие'), ('intimacy', 'Близость'), ('gratitude', 'Благодарность'), ('children', 'Дети'), ('finances', 'Финансы'), ('relatives', 'Родственники'), ('romance', 'Романтика')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='practice',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
