# Generated by Django 5.0.6 on 2026-06-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0008_dailyassignment_is_ai_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentslot',
            name='slot_type',
            field=models.CharField(choices=[('main', 'Практика дня'), ('conversation', 'Тема разговора'), ('gesture', 'Маленький жест любви'), ('activity', 'Семейная активность'), ('ritual', 'Ритуал пары'), ('growth', 'Рекомендация для роста')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='practice',
            name='slot_type',
            field=models.CharField(choices=[('main', 'Практика дня'), ('conversation', 'Тема разговора'), ('gesture', 'Маленький жест любви'), ('activity', 'Семейная активность'), ('ritual', 'Ритуал пары'), ('growth', 'Рекомендация для роста')], db_index=True, max_length=20),
        ),
    ]
