# Generated by Django 5.0.6 on 2026-06-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_article_training_i18n'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='academy_art_categor_e9fe7e_idx',
            old_name='academy_art_cat_pub_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='academy_art_slug_2a5c4f_idx',
            old_name='academy_art_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='userachievement',
            new_name='academy_use_user_id_2a850e_idx',
            old_name='academy_ua_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userarticleprogress',
            new_name='academy_use_user_id_ae20a0_idx',
            old_name='academy_uap_user_idx',
        ),
        migrations.RenameIndex(
            model_name='usermicropracticelog',
            new_name='academy_use_user_id_2065c5_idx',
            old_name='academy_umpl_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='userprogramdayprogress',
            new_name='academy_use_enrollm_9f1e64_idx',
            old_name='academy_updp_enrollment_idx',
        ),
        migrations.RenameIndex(
            model_name='userprogramenrollment',
            new_name='academy_use_user_id_9ffbf7_idx',
            old_name='academy_upe_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='usertrainingprogress',
            new_name='academy_use_user_id_c795a2_idx',
            old_name='academy_utp_user_idx',
        ),
    ]
