# Generated by Django 5.0.6 on 2026-06-18 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0003_couple_children_count_couple_has_children_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dialog_type', models.CharField(choices=[('coach', 'Консультант'), ('mediator', 'Медиатор')], default='coach', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_conversations', to='couples.couple')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_coach_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.coachconversation')),
            ],
            options={
                'db_table': 'ai_coach_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coachconversation',
            index=models.Index(fields=['user', '-created_at'], name='ai_coach_co_user_id_108702_idx'),
        ),
        migrations.AddIndex(
            model_name='coachconversation',
            index=models.Index(fields=['couple', 'dialog_type'], name='ai_coach_co_couple__e44e11_idx'),
        ),
        migrations.AddIndex(
            model_name='coachmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_coach_me_convers_1cfb6d_idx'),
        ),
    ]
