# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('diagnostic', 'Диагностика'), ('progress', 'Прогресс')], max_length=30)),
                ('status', models.CharField(choices=[('generating', 'Генерируется'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='generating', max_length=20)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('share_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('share_expires_at', models.DateTimeField(blank=True, null=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='couples.couple')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
