# Generated by Django 5.0.6 on 2026-06-15 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0004_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.analyticsresult'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['couple', '-created_at'], name='reports_couple__8b6c49_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['share_token'], name='reports_share_t_7ed0d1_idx'),
        ),
    ]
